src/objects/Invoice_Statement__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <label>Invoice Statement</label>
    <nameField>
        <displayFormat>INV-{0000}</displayFormat>
        <label>Invoice Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Invoice Statements</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Invoice_Statement__c</fullName>
        <label>Invoice Statement</label>
        <referenceTo>Invoice_Statement__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Unit_Price__c</fullName>
        <label>Unit Price</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Units_Sold__c</fullName>
        <label>Units Sold</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is a description of the merchandise. This is a required field.</description>
        <inlineHelpText>Use up to 255 characters</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of the item. This is required</description>
        <inlineHelpText>Enter a dollar amount.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Inventory__c</fullName>
        <label>Total Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestDataFactory.cls
@isTest
public class TestDataFactory {
	public static Invoice_Statement__c createOneInvoiceStatement (Boolean withLineItem) {
		Invoice_Statement__c testInvoice = createInvoiceStatement();
		if (withLineItem == true) {
			Merchandise__c m = createMerchandiseItem('Orange Juice');
			
			AddLineItem(testInvoice, m);
		}
		return testInvoice;
	}
	
	private static Merchandise__c createMerchandiseItem(String merchName) {
		Merchandise__c m = new Merchandise__c(Name=merchName, Description__c='Fresh Juice', Price__c=2, Total_Inventory__c=1000);
		insert m;
		return m;
	}
	
	private static Invoice_Statement__c createInvoiceStatement() {
		Invoice_Statement__c inv = new Invoice_Statement__c(Description__c='Test Invoice');
		insert inv;
		return inv;
	}
	
	private static Line_Item__c AddLineItem (Invoice_Statement__c inv, Merchandise__c m) {
		Line_Item__c lineItem = new Line_Item__c(Invoice_Statement__c = inv.Id, Merchandise__c = m.Id, Unit_Price__c = m.Price__c, Units_Sold__c = (Double)(10*Math.random()+1));
		insert lineItem;
		return lineItem;
	}
}