src/objects/Line_Item__c.object
<CustomObject>
    <fields>
        <fullName>Merchandise__c</fullName>
        <label>Merchandise</label>
        <referenceTo>Merchandise__c</referenceTo>
        <relationshipLabel>Line Items</relationshipLabel>
        <relationshipName>Line_Items</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Line Item</label>
    <nameField>
        <label>Line Item Number</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Line Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is a description of the merchandise. This is a required field.</description>
        <inlineHelpText>Use up to 255 characters</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of the item. This is required</description>
        <inlineHelpText>Enter a dollar amount.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Inventory__c</fullName>
        <label>Total Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestCleanUpBatchClass.cls
@isTest
private class TestCleanUpBatchClass {
	static testmethod void test() {
		
		String query = 'SELECT Id, CreatedDate FROM Merchandise__c ' + 'WHERE Id NOT IN (SELECT Merchandise__c FROM Line_Item__c)';
		
	    Merchandise__c[] ml = new List<Merchandise__c>();
        for (Integer i=0;i<10;i++) {
           Merchandise__c m = new Merchandise__c(
               Name='Merchandise ' + i,
               Description__c='Some description',
               Price__c=2,
               Total_Inventory__c=100);
           ml.add(m);
       }
       insert ml;
       
       Test.startTest();
       CleanUpRecords c = new CleanupRecords(query);
       Database.executeBatch(c);
       Test.stopTest();
       
       Integer i = [SELECT COUNT() FROM Merchandise__c];
       System.assertEquals(i,0);
	}

}