src/objects/Merchandise__c.object
<CustomObject>
    <fields>
        <fullName>Description__c</fullName>
        <description>This is a description of the merchandise. This is a required field.</description>
        <inlineHelpText>Use up to 255 characters</inlineHelpText>
        <label>Description</label>
        <required>true</required>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Price__c</fullName>
        <description>Price of the item. This is required</description>
        <inlineHelpText>Enter a dollar amount.</inlineHelpText>
        <label>Price</label>
        <precision>18</precision>
        <required>true</required>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Inventory__c</fullName>
        <label>Total Inventory</label>
        <precision>18</precision>
        <required>true</required>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>Merchandise</label>
    <nameField>
        <label>Merchandise Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Merchandise</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/MerchandiseManager.cls
@RestResource(urlMapping='/Merchandise/*')
global with sharing class MerchandiseManager {
	
	@HttpGet
	global static Merchandise__c getMerchandiseById() {
		RestREquest req = RestContext.request;
		String merchId = req.requestuRI.substring(req.requestURI.lastIndexOf('/')+1);
		
		Merchandise__c result = [SELECT Name,Description__c,Price__c,Total_Inventory__c FROM Merchandise__c WHERE Id = :merchId];
		return result;
	}
	
	@HttpPost
	global static STring createMerchandise(String name, String description, Decimal price, Double inventory) {
		Merchandise__c m = new Merchandise__c (Name=name, Description__c=description, Price__c=price, Total_Inventory__c=inventory);
		insert m;
		return m.Id;
	}
}